### ISSUE TITLE
Error in Flatly's buttons-

### ISSUE THREAD

**Issue by alainus** [maxim/bootswatch-rails#41]
In _bootswatch.scss, line 256, 260, 264: 

``` scss
    .btn-large {
        padding: $paddingLarge;
    }

    .btn-small {
        padding: $paddingSmall;
    }

    .btn-mini {
        padding: $paddingMini;
    }
```

Should be:

``` scss
    &.btn-large {
        padding: $paddingLarge;
    }

    &.btn-small {
        padding: $paddingSmall;
    }

    &.btn-mini {
        padding: $paddingMini;
    }
```
