### ISSUE TITLE
glyphicons-halflings not resolving

### ISSUE THREAD

**Issue by jjwilliams** [maxim/bootswatch-rails#76]
Once I found this gem, I was able to get mostly everything working (templates load, colors, menus, etc...). Everything except the fonts. 

It looks like its hitting /fonts/bootstrap/... instead of /assets/...

http://localhost:3000/fonts/bootstrap/glyphicons-halflings-regular.woff  --> 404
http://localhost:3000/fonts/bootstrap/glyphicons-halflings-regular.ttf      --> 404

Any idea why this might be?

**Comment by jjwilliams** [comment]
3.3.1.0

**Comment by jjwilliams** [comment]
Any ideas on this?

**Comment by esbanarango** [comment]
@jjwilliams could you change you `appplication.css.scss` and add `@import "bootstrap-sprockets";`

`````scss

@import "bootswatch/united/variables";
@import "bootstrap-sprockets";
@import "bootstrap";

body {
    padding-top: 60px;
}

@import "bootswatch/united/bootswatch";
@import "font-awesome-sprockets";
@import "font-awesome"

``````
